# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-166943279-1'
google-GTM: 'GTM-MG2QXKM'

menu: 
  - name: Pet Projects
    submenu:
      - name: CSV Viewer
        link: /projects/csv-viewer
      - name: Plain Test
        link: /projects/plain-test
      - name: Kafka Tool
        link: /projects/kafka-tool
  - name: Apresentações
    submenu:
      - name: "Kafka: Uma introdução para Desenvolvedores e Arquitetos"
        link: /presentations/2020-03-26-sou-java-kafka
      - name: "Usando Java CDI em projetos Jakarta EE ou Microprofile"
        link: /presentations/2019-09-14-sou-java-cdi
      - name: "A Filosofia do Design de Código"
        link: /presentations/2021-08-26-a-filosofia-do-design-de-codigo
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: Séries
    link: /series
  - name: Sobre
    link: /about
  - name: Livros Recomendados
    link: /books
  - name: Redes Sociais
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/vepo
      - name: LinkedIn
        icon: linkedin-square
        link: http://www.linkedin.com/in/victorosorio
      - name: Twitter
        icon: twitter
        link: https://twitter.com/vepo
    
